[package]
name = "vmc_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring = "0.16.20"
rmp-serde = "1.1.1"
serde = { version = "1.0.160", features = ["derive"] }
